spring:
  data:
    mongodb:
      uri: mongodb://loser:loser@119.91.155.174:27017/loser?authMechanism=SCRAM-SHA-1
      dynamic:
        datasource:
          slave_1:
            uri: mongodb://loser:loser@119.91.155.174:27017/loser?authMechanism=SCRAM-SHA-1
          slave_2:
            uri: mongodb://loser:loser@119.91.155.174:27017/loser?authMechanism=SCRAM-SHA-1
mogo:
  logic:
    open: true
    auto-fill: true
    logic-delete-field: logicDel
    logic-delete-value: 1
    logic-not-delete-value: 0
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
#knife4j:
#  enable: true
#  setting:
#    language: zh-CN
#    enableVersion: true
#  production: false
